### ISSUE TITLE
rport in REGISTER is not respected on outbound INVITE 

### ISSUE THREAD

**Issue by tinpotnick** [drachtio/drachtio-server#207]
[drachtio.log](https://github.com/drachtio/drachtio-server/files/8877121/drachtio.log)

The log is not quite a normal nat issue - but the principle is the same. Zoiper REGISTERS and uses rport in the via header so the REGISTER works correctly - packets are sent back to the destination - not the IP reported in the SIP packet.

If sned an INVITE to that registration using the contact string which is provided by Drachtio in the REGISTER Drachtio sends this packet to the IP in the contact string - which refers to the SIP REGISTRATION.

RFC 3581, page 7, discusses the rport in a REGISTER. I am not sure what responsibility Drachtio should have and what should be handled in the node application.

Looking at the log Drachtio responds with rport=53978 with a via with the correct 127.0.0.1. I am also unsure what should be corrected by the client (the RFC appears a little ambiguous on this).

My initial guess is that an INVITE Drachtio sends out should go to the same place as in the REGISTER packet with an rport.

**Comment by davehorton** [comment]
This doesn't look like a bug to me.  The Contact header in the REGISTER we receive is this:
```
 Contact: <sip:1000@82.19.206.102:53978;rinstance=cfe11a374edf9e5b;transport=UDP>
```

So, when we want to send a call to that registered client we send it to the specified Contact sip uri:
```
send 713 bytes to udp/[82.19.206.102]:53978 at 08:12:59.461806:
INVITE sip:1000@82.19.206.102:53978;rinstance=cfe11a374edf9e5b;transport=UDP SIP/2.0
```

This fails because apparently nothing is listening at that ip:port
```
 nta: INVITE (52870597): Connection refused (111) with udp/[82.19.206.102]:53978
```

However, that is not a problem with the drachtio framework, it appears more a problem with the client AFAIK

In short, the client registers a sip uri where it wants to be contacted, but requests sent to that sip uri fail

**Comment by davehorton** [comment]
That would be up to your application to do.
